cmake_minimum_required(VERSION 3.0)

add_executable(VertexLayoutTest ${TESTS_DIR}/VertexLayoutTest.cpp)
target_link_libraries(VertexLayoutTest Catch2)
target_link_libraries(VertexLayoutTest vertex-layout)
target_link_libraries(VertexLayoutTest vertex-buffer)

add_executable(GameObjectTest ${TESTS_DIR}/GameObjectTest.cpp)
target_link_libraries(GameObjectTest index-buffer)
target_link_libraries(GameObjectTest vertex-buffer)
target_link_libraries(GameObjectTest vertex-array)
target_link_libraries(GameObjectTest vertex-layout)
target_link_libraries(GameObjectTest renderer)
target_link_libraries(GameObjectTest camera)
target_link_libraries(GameObjectTest game-object)
target_link_libraries(GameObjectTest core)
target_link_libraries(GameObjectTest ${SOIL_STATIC_LIB})
target_link_libraries(GameObjectTest glew)
target_link_libraries(GameObjectTest glfw)
target_link_libraries(GameObjectTest glm_static)
target_link_libraries(GameObjectTest opengl32)
target_link_libraries(GameObjectTest m)

add_executable(CameraTest ${TESTS_DIR}/CameraTest.cpp)
target_link_libraries(CameraTest Catch2)
target_link_libraries(CameraTest camera)

add_executable(GLShaderTest ${TESTS_DIR}/TestGLShader.cpp)
target_link_libraries(GLShaderTest glshader)
target_link_libraries(GLShaderTest renderer)
target_link_libraries(GLShaderTest index-buffer)
target_link_libraries(GLShaderTest vertex-buffer)
target_link_libraries(GLShaderTest vertex-array)
target_link_libraries(GLShaderTest vertex-layout)
target_link_libraries(GLShaderTest camera)
target_link_libraries(GLShaderTest game-object)
target_link_libraries(GLShaderTest core)
target_link_libraries(GLShaderTest ${SOIL_STATIC_LIB})
target_link_libraries(GLShaderTest glew)
target_link_libraries(GLShaderTest glfw)
target_link_libraries(GLShaderTest glm_static)
target_link_libraries(GLShaderTest opengl32)
target_link_libraries(GLShaderTest m)

