cmake_minimum_required(VERSION 3.0)

add_executable(test ${TESTS_DIR}/test.cpp)
target_link_libraries(test Catch2)

add_executable(VertexLayoutTest ${TESTS_DIR}/VertexLayoutTest.cpp)
target_link_libraries(VertexLayoutTest Catch2)
target_link_libraries(VertexLayoutTest vertex-layout)
target_link_libraries(VertexLayoutTest vertex-buffer)

add_executable(GameObjectTest ${TESTS_DIR}/GameObjectTest.cpp)
target_link_libraries(GameObjectTest index-buffer)
target_link_libraries(GameObjectTest vertex-buffer)
target_link_libraries(GameObjectTest vertex-array)
target_link_libraries(GameObjectTest vertex-layout)
target_link_libraries(GameObjectTest renderer)
target_link_libraries(GameObjectTest camera)
target_link_libraries(GameObjectTest game-object)
target_link_libraries(GameObjectTest core)
target_link_libraries(GameObjectTest ${SOIL_STATIC_LIB})
target_link_libraries(GameObjectTest glew)
target_link_libraries(GameObjectTest glfw)
target_link_libraries(GameObjectTest glm_static)
target_link_libraries(GameObjectTest opengl32)
target_link_libraries(GameObjectTest m)

add_executable(CameraTest ${TESTS_DIR}/CameraTest.cpp)
target_link_libraries(CameraTest Catch2)
target_link_libraries(CameraTest camera)